<?php
// This file generated by Propel 1.5.4 convert-conf target
return array (
  'BaseSession' => 'colony/om/BaseSession.php',
  'BaseSessionPeer' => 'colony/om/BaseSessionPeer.php',
  'BaseSessionQuery' => 'colony/om/BaseSessionQuery.php',
  'BaseUser' => 'colony/om/BaseUser.php',
  'BaseUserPeer' => 'colony/om/BaseUserPeer.php',
  'BaseUserQuery' => 'colony/om/BaseUserQuery.php',
  'Session' => 'colony/Session.php',
  'SessionPeer' => 'colony/SessionPeer.php',
  'SessionQuery' => 'colony/SessionQuery.php',
  'SessionTableMap' => 'colony/map/SessionTableMap.php',
  'User' => 'colony/User.php',
  'UserPeer' => 'colony/UserPeer.php',
  'UserQuery' => 'colony/UserQuery.php',
  'UserTableMap' => 'colony/map/UserTableMap.php',
);